spring.datasource.url=jdbc:mysql://localhost:3306/combat_tracker
spring.datasource.username=root
spring.datasource.password=SpoderMaNN310*&

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
